export const TEXT_CONSTANTS = {
  HEADER: {
    DEFAULT_TITLE: 'Cash acceleration',
    DEFAULT_SUBTITLE: 'Place to create new cash kicks to run your business',
    HOME_TITLE: 'Home Overview',
    HOME_SUBTITLE: 'Welcome back to Seeder financial dashboard',
  },
  AVATAR: {
    DEFAULT_SRC: 'https://i.pravatar.cc/150?img=47',
    DEFAULT_ALT: 'Kane Cooper',
    DEFAULT_NAME: 'Kane Cooper',
    EDIT_PROFILE: 'Edit Profile',
    MANAGE_SUBSCRIPTIONS: 'Manage Subscriptions',
    HELP: 'Help',
    SETTINGS: 'Settings',
    LOG_OUT: 'Log Out',
  },
  SIDEBAR: {
    LOGO_TEXT: 'Seeder',
    NAV_HOME: 'Home',
    NAV_CASH_ACCELERATION: 'Cash Acceleration',
    WATCH_HOW_TO: 'Watch how to',
    PATHS: {
      HOME: '/home',
      CASH_ACCELERATION: '/cash-acceleration',
    },
  },
  LAUNCH_CARD: {
    TITLE: 'Launch a new Cash Kick',
    PREFIX_TEXT: 'You have upto',
    SUFFIX_TEXT: 'available for a new cash advance',
    BUTTON_TEXT: 'New Cash Kick',
    DEFAULT_AMOUNT: '$880,000.00',
  },
  METRICS: {
    TERM_CAP: {
      LABEL: 'Term cap',
      TOOLTIP: 'Maximum tenure allowed for new cash advances',
    },
    AVAILABLE_CREDIT: {
      LABEL: 'Available credit',
      TOOLTIP: 'Total credit available for instant withdrawal',
    },
    MAX_INTEREST_RATE: {
      LABEL: 'Max interest rate',
      TOOLTIP: 'Maximum applicable rate across contracts',
    },
    DEFAULT_TOOLTIP: 'Information regarding this metric',
  },
  CONTRACTS_TABLE: {
    TITLE: 'Cash acceleration',
    TITLE_TOOLTIP: 'View and manage active cash advance contracts',
    SYNC_TEXT: 'Sync Now',
    TAB_MY_CONTRACTS: 'My Contracts',
    TAB_MY_CASH_KICKS: 'My Cash Kicks',
    COL_NAME: 'Name',
    COL_STATUS: 'Status',
    COL_TYPE: 'Type',
    COL_PER_PAYMENT: 'Per payment',
    COL_TOTAL_FINANCED: 'Total financed',
    COL_TOTAL_AVAILABLE: 'Total available',
    EMPTY_CONTRACTS: 'No active contracts available.',
    EMPTY_CASH_KICKS: 'No launched cash kicks available.',
  },
  MODAL: {
    TITLE: 'Launch a new Cash Kick',
    NAME_LABEL: 'Name your cash kick',
    NAME_PLACEHOLDER: 'Enter cash kick name',
    TABLE_LABEL: 'Select contracts to advance',
    COL_NAME: 'Name',
    COL_PER_PAYMENT: 'Per Payment',
    COL_AVAILABLE_AMOUNT: 'Available Amount',
    EMPTY_CONTRACTS: 'No available contracts to advance.',
    SUMMARY_TITLE: 'Summary Details',
    SELECTED_CONTRACTS: 'Selected Contracts:',
    TOTAL_SELECTED_VALUE: 'Total Selected Value (Payback):',
    RATE_FEE_PREFIX: 'Rate Fee',
    TOTAL_ADVANCE: 'Total Advance (Payout):',
    EXCEED_WARNING_PREFIX: '* Selected amount exceeds your available credit of ',
    CANCEL_BTN: 'Cancel',
    LAUNCH_BTN: 'Launch Cash Kick',
    LAUNCHING_BTN: 'Launching...',
  },
  HOME_PAGE: {
    CARD_TITLE: 'Home Overview',
    CARD_DESCRIPTION: "Select 'Cash Acceleration' from the sidebar navigation to view active contracts and launch cash advances.",
  },
};
